name: markdown-lint
run-name: Linting markdown files

on:
  push:
    <<: &filters
    branches: [main, develop]
    paths: ["**.md", "**.mdx"]
  pull_request:
    <<: *filters #reference syntax

concurrency:
  group: markdown-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: recursivezero/action-club/.github/actions/md-lint@v0.2.58
